## scoring.gd — Chronos (score) calculation for a Cohesion Pulse (chain).
## All methods are static — no instance needed.
class_name Scoring
extends RefCounted

## Calculate the Chronos generated by a completed chain.
## Returns a Dictionary with all scoring components.
static func calculate(chain: Chain) -> Dictionary:
	if chain.is_empty():
		return { "chips": 0, "mult": 1, "total": 0,
				 "length": 0, "doubles": 0 }

	var chips:   int = 0
	var mult:    int = 1
	var doubles: int = 0

	# Sum raw pip values (Chronos charge)
	for tile in chain.tiles:
		chips += tile.total_pips()
		if tile.is_double():
			doubles += 1

	# Double resonance bonus
	mult += doubles

	# Chain length (cohesion) bonus
	var length: int = chain.length()
	if length >= Constants.CHAIN_BONUS_LARGE:
		mult += 2
	elif length >= Constants.CHAIN_BONUS_SMALL:
		mult += 1

	return {
		"chips":   chips,
		"mult":    mult,
		"total":   chips * mult,
		"length":  length,
		"doubles": doubles,
	}

## Convenience: score and return only the Chronos total.
static func total(chain: Chain) -> int:
	return calculate(chain)["total"]
